// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApgZWweXFYLPJ8YKUsXnBdZF3JoaGuT3U',
    appId: '1:443655647591:web:61d30eee05d018ceefffc2',
    messagingSenderId: '443655647591',
    projectId: 'nutridiary-testrun',
    authDomain: 'nutridiary-testrun.firebaseapp.com',
    databaseURL: 'https://nutridiary-testrun-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nutridiary-testrun.firebasestorage.app',
    measurementId: 'G-TMR000JQB3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZz3C4K8_3Wq-Fswn-dfIjB6OdZNaWAFk',
    appId: '1:443655647591:android:535a40f8e19ec04befffc2',
    messagingSenderId: '443655647591',
    projectId: 'nutridiary-testrun',
    databaseURL: 'https://nutridiary-testrun-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nutridiary-testrun.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZOWCtTehFe11ZKn18oKLIOiE2hd9zvnE',
    appId: '1:443655647591:ios:3c278728f396baa8efffc2',
    messagingSenderId: '443655647591',
    projectId: 'nutridiary-testrun',
    databaseURL: 'https://nutridiary-testrun-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nutridiary-testrun.firebasestorage.app',
    iosBundleId: 'com.example.flutterNutridiary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZOWCtTehFe11ZKn18oKLIOiE2hd9zvnE',
    appId: '1:443655647591:ios:3c278728f396baa8efffc2',
    messagingSenderId: '443655647591',
    projectId: 'nutridiary-testrun',
    databaseURL: 'https://nutridiary-testrun-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nutridiary-testrun.firebasestorage.app',
    iosBundleId: 'com.example.flutterNutridiary',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApgZWweXFYLPJ8YKUsXnBdZF3JoaGuT3U',
    appId: '1:443655647591:web:725f25582069a75fefffc2',
    messagingSenderId: '443655647591',
    projectId: 'nutridiary-testrun',
    authDomain: 'nutridiary-testrun.firebaseapp.com',
    databaseURL: 'https://nutridiary-testrun-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nutridiary-testrun.firebasestorage.app',
    measurementId: 'G-7GTH3W9DD5',
  );
}
