import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_database/firebase_database.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:provider/provider.dart';
import 'screens/login_screen.dart';
import 'providers/app_state_provider.dart';
import 'providers/item_provider.dart';
import 'providers/page_index_provider.dart';
import 'package:firebase_core/firebase_core.dart'; // Import Firebase Core
import 'firebase_options.dart'; // <-- Ensure this import is present and NOT commented out
import 'widgets/home_screen.dart'; // <-- NEW: Import HomeScreen from widgets/home_screen.dart

// Make main async to allow for Firebase initialization
void main() async { // <-- NEW: Make main async
  // Required for any async operations before runApp
  WidgetsFlutterBinding.ensureInitialized();

  // --- Initialize Firebase ---
  // This line MUST be present and NOT commented out!
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform, // This uses the file generated by flutterfire configure
  );

  // Now that Firebase is initialized, it's safe to run your app
  SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp]);
  runApp(
    MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => AppStateProvider()),
        ChangeNotifierProvider(create: (_) => ItemProvider()), // Updated provider
        ChangeNotifierProvider(create: (_) => PageIndexProvider()),
        // SessionProvider removed
      ],
      child: const MyApp(), // Remove SessionManager wrapper
    ),
  );
}

void readAndPrintUserData() async {
  final user = FirebaseAuth.instance.currentUser; // Get the currently logged-in user

  if (user != null) {
    final uid = user.uid; // Get the user's unique ID

    // Create a reference to the specific user's data node in Realtime Database
    final userRef = FirebaseDatabase.instance.ref('users/$uid');

    try {
      // Read the data from the database path one time
      final snapshot = await userRef.get();

      if (snapshot.exists) {
        debugPrint('--- RTDB Data for user $uid ---');
        // snapshot.value contains the data. Use debugPrint for Flutter debugging
        debugPrint(snapshot.value.toString()); // Print the entire data structure
        debugPrint('----------------------------');

        // You can also specifically check if the 'username' field exists and its value
        if (snapshot.child('username').exists) {
          debugPrint('Username field found: ${snapshot.child('username').value}');
        } else {
          debugPrint('Username field NOT found in snapshot.value');
        }


      } else {
        debugPrint('User node does NOT exist in RTDB for UID: $uid');
      }
    } catch (e) {
      // Handle any errors during the read operation
      debugPrint('Error reading user data from RTDB: $e');
    }
  } else {
    debugPrint('No user is currently signed in.');
  }
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    final appState = Provider.of<AppStateProvider>(context);

    // --- NEW: Conditional rendering based on loading and logged-in state ---
    Widget homeScreen;
    if (appState.isLoading) {
      // Show a simple loading screen if AppStateProvider.isLoading is true
      homeScreen = const Scaffold( // Use Scaffold for basic structure
        body: Center( // Center the indicator
          child: CircularProgressIndicator(), // Standard loading indicator
        ),
      );
    } else if (appState.isLoggedIn) {
      // User is logged in.
      readAndPrintUserData();
      debugPrint('MyApp: User is a regular user. Rendering HomeScreen.');
      homeScreen = const HomeScreen();
    } else {
      // Show LoginScreen if not loading and user is NOT logged in
      // Remove the onLogin parameter from LoginScreen here as navigation is handled by MyApp
      homeScreen = const LoginScreen();
    }
    // --- End of NEW conditional rendering ---

    return MaterialApp(
      debugShowCheckedModeBanner: false,
      themeMode: appState.isDarkMode ? ThemeMode.dark : ThemeMode.light,
      theme: ThemeData.light(),
      darkTheme: ThemeData.dark(),
      // Assign the determined homeScreen widget
      home: homeScreen,
    );
  }
}
